// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TUP.MateriasMVC.Data;

#nullable disable

namespace TUP.MateriasMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260528010148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TUP.MateriasMVC.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "López",
                            Dni = "40111222",
                            Email = "alopez@mail.com",
                            Nombre = "Agustín"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Martínez",
                            Dni = "41222333",
                            Email = "bmartinez@mail.com",
                            Nombre = "Brenda"
                        });
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Materia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Anio")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cuatrimestre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Materias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Anio = 1,
                            Cuatrimestre = 1,
                            Descripcion = "Intro a C#",
                            Nombre = "Programación I",
                            ProfesorId = 1
                        },
                        new
                        {
                            Id = 2,
                            Anio = 1,
                            Cuatrimestre = 1,
                            Descripcion = "POO práctica",
                            Nombre = "Laboratorio I",
                            ProfesorId = 2
                        });
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.MateriaAlumno", b =>
                {
                    b.Property<int>("MateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Condicion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("TEXT");

                    b.HasKey("MateriaId", "AlumnoId");

                    b.HasIndex("AlumnoId");

                    b.ToTable("MateriaAlumnos");

                    b.HasData(
                        new
                        {
                            MateriaId = 1,
                            AlumnoId = 1,
                            Condicion = "Regular",
                            FechaInscripcion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MateriaId = 1,
                            AlumnoId = 2,
                            Condicion = "Libre",
                            FechaInscripcion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MateriaId = 2,
                            AlumnoId = 1,
                            Condicion = "Regular",
                            FechaInscripcion = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Legajo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Profesores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Medina",
                            Email = "cmedina@tup.edu.ar",
                            Legajo = "P001",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Torres",
                            Email = "ltorres@tup.edu.ar",
                            Legajo = "P002",
                            Nombre = "Luciana"
                        });
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Materia", b =>
                {
                    b.HasOne("TUP.MateriasMVC.Models.Profesor", "Profesor")
                        .WithMany("Materias")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.MateriaAlumno", b =>
                {
                    b.HasOne("TUP.MateriasMVC.Models.Alumno", "Alumno")
                        .WithMany("MateriaAlumnos")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TUP.MateriasMVC.Models.Materia", "Materia")
                        .WithMany("MateriaAlumnos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Alumno", b =>
                {
                    b.Navigation("MateriaAlumnos");
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Materia", b =>
                {
                    b.Navigation("MateriaAlumnos");
                });

            modelBuilder.Entity("TUP.MateriasMVC.Models.Profesor", b =>
                {
                    b.Navigation("Materias");
                });
#pragma warning restore 612, 618
        }
    }
}
